export const apiUrls = {
  LOGIN: "frontend/login",
  GOOGLE_AUTH: "frontend/auth/google",
  REGISTER: "frontend/customer/register",
  LOGOUT: "frontend/logout",
  GETMYPROFILE: "frontend/customer/get-profile",
  CHANGE_PASSWORD: "frontend/customer/change-password",
  UPDATE_PROFILE: "frontend/customer/update-profile",
  NavigationAPI: "frontend-categories",
  NavigationAPIHOME: "frontend-categories?category_type=home",
  FEATURED_PRODUCTS: "frontend/categories/featured-products",
  FEATURED_BRAND_PRODUCTS: "frontend/brands/featured-products",
  BLOGS: "frontend/blogs",
  MAIN_CATEGORY_PAGES: (slug: string) => `frontend/category-pages/by-url/${slug}`,
  PRODUCTS_FILTERS: "frontend/products/filters/get-filters",
  PRODUCTS_LISTING: "frontend/products/filters/get-products",
  PRODUCT_DETAIL: (slug: string) => `frontend/products/${slug}`,
  ALTERNATE_PRODUCTS: (slug: string) => `frontend/products/${slug}/alternates`,
  SIMILAR_PRODUCTS: (slug: string) => `frontend/products/${slug}/similar`,
  RECOMMENDED_PRODUCTS: (slug: string) =>
    `frontend/products/${slug}/recommended-product`,
  BRANDS: "frontend/brands",
  SEARCH: "frontend/search",
  CART_GET: "frontend/carts",
  CART_ADD: "frontend/carts/add",
  CART_ADD_MULTIPLE: "frontend/carts/add-multiple",
  CART_UPDATE_QTY: (id: number) => `frontend/carts/update-quantity/${id}`,
  CART_REMOVE: (id: number) => `frontend/carts/remove/${id}`,
  CART_EMPTY: "frontend/carts/empty",
  WISHLIST_GET: "frontend/wishlist",
  WISHLIST_ADD: "frontend/wishlist/add",
  WISHLIST_REMOVE: "frontend/wishlist/remove",
  WISHLIST_ADD_MULTIPLE: "frontend/wishlist/add-multiple",
  SAVE_FOR_LATER: "frontend/save-for-later",
  SAVE_FOR_LATER_REMOVE: "frontend/remove-from-save-for-later",
  GET_CUSTOMER_ADDRESS: "frontend/customer-address",
  ADD_CUSTOMER_ADDRESS: "frontend/customer-address",
  UPDATE_CUSTOMER_ADDRESS: (id: number) => `frontend/customer-address/${id}`,
  DELETE_CUSTOMER_ADDRESS: (id: number) => `frontend/customer-address/${id}`,
  DEFAULT_CUSTOMER_ADDRESS: "frontend/customer-address/default",
  CUSTOMER_COUNTS: "frontend/customer/counts",
  BRAND_BY_SLUG: (slug: string) => `frontend/brand-by-slug/${slug}`,
  COUNTRIES: "frontend/countries",
  STATES: "frontend/states",
  CITIES: "frontend/cities",
  SLIDER: (id: number) => `frontend/sliders/${id}`,
  MADE_TO_ORDER: "frontend/made-to-orders",
  SQUARE_PAYMENT: "frontend/payment-square",
  PLACE_ORDER: "frontend/orders",
  ADD_RECENT_PRODUCT: "frontend/recent-products/add",
  GET_RECENT_PRODUCTS: (page: number) => `frontend/recent-products?page=${page}`,
  GUEST_VIEW_PRODUCT: "frontend/guest/view-product",
  GUEST_RECENT_PRODUCTS: (guestToken: string, page: number) =>
    `frontend/guest/recent-products?guest_token=${guestToken}&page=${page}`,
  ORDER_DETAIL: (id: number) => `frontend/orders/${id}`,
  PAYMENT_HISTORY: "frontend/payments",
  LOCATION: "frontend/location",
  TAX_RATE: "frontend/tax/rate",
  FORGOT_PASSWORD: "auth/forgot-password",
  RESET_PASSWORD: "auth/reset-password",
  COUNTRY_LOOKUP: "frontend/countries/lookup",
  CHECK_COUPON: "customer/check-coupon",
};
